apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "prometheus-salesforce-exporter.fullname" . }}
  labels:
    {{- include "prometheus-salesforce-exporter.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "prometheus-salesforce-exporter.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "prometheus-salesforce-exporter.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "prometheus-salesforce-exporter.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: HTTP_PORT
              value: {{ .Values.http.port | quote }}
            - name: POLL_INTERVAL
              value: {{ .Values.pollInterval | quote }}
            - name: SALESFORCE_BASE_URL
              value: {{ .Values.salesforce.baseUrl | quote }}
            - name: SALESFORCE_CLIENT_ID
              value: {{ .Values.salesforce.clientId | quote }}
            - name: SALESFORCE_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "prometheus-salesforce-exporter.secretName" . }}
                  key: SALESFORCE_CLIENT_SECRET
            - name: SALESFORCE_USERNAME
              value: {{ .Values.salesforce.username | quote }}
            - name: SALESFORCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "prometheus-salesforce-exporter.secretName" . }}
                  key: SALESFORCE_PASSWORD
            - name: SALESFORCE_API_VERSION
              value: {{ .Values.salesforce.apiVersion | quote }}
            - name: SALESFORCE_GRANT_TYPE
              value: {{ .Values.salesforce.grantType | quote }}
          ports:
            - name: http
              containerPort: {{ .Values.http.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: http
          readinessProbe:
            httpGet:
              path: /health
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
