apiVersion: v1
kind: Secret
metadata:
  name: {{ include "prometheus-salesforce-exporter.secretName" . }}
  labels:
    {{- include "prometheus-salesforce-exporter.labels" . | nindent 4 }}
type: Opaque
data:
  SALESFORCE_CLIENT_SECRET: {{ required "salesforce.clientSecret is required" .Values.salesforce.clientSecret | b64enc | quote }}
  SALESFORCE_PASSWORD: {{ required ".salesforce.password is required" .Values.salesforce.password | b64enc | quote }}
